### PR TITLE
Properly use gsa-tts/terraform-cloudgov modules

### LINKED ISSUE #84: Clarify terraform/README
The `initial setup` section of terraform/README is unclear about whether it refers to the initial run of bootstrap for the entire project (which is what it does) vs. the initial setup for every dev on the project (not what is intended).

Reword the README to clarify the use cases for project-wide vs individual dev setup.

### LINKED ISSUE #95: Update terraform generator to use gsa-tts modules
And add module versions

### PR DESCRIPTION
**Pull request by rahearn**
The previous implementation was just incredibly broken once development happened on terraform-cloudgov and not here.

Changes:

1. Updates for cf-cli@8
2. Clean up the terraform modules to match what the 1.0 modules release actually needs and set the version constraint to keep working. 🤦🏻 (closes #95)
3. Update terraform/README to be more friendly to the second and third developer on the team (closes #84)

### CODE REVIEW

**Review by zjrgov — DISMISSED** [review]
I still don't have the context nor do I know much of anything about Terraform but the markdown at least reads well to me :-)

And I'm supposing wherever those shell scripts get run it's safe to assume they have `jq`?

**Comment by rahearn** [comment]
> And I'm supposing wherever those shell scripts get run it's safe to assume they have jq?

`jq` is mentioned in the Readme and included in the `Brewfile` for installing dependencies, though it probably wouldn't be a bad idea to test for it and fail fast if it's not found.

**Review by jskinne3 — APPROVED** [review]
Looks good. I appreciate that you clarified the distinction between initial project and developer setup instructions.

**Review by zjrgov — APPROVED** [review]
I somehow never heard of Brewfiles, very pleased to know about them now.

**Pull request merged**
